[tool.poetry]
name = "roostai"
version = "0.1.0"
description = "Univeristy-Centered Chatbot"
authors = ["Vansh Nagpal <2002vansh@gmail.com>"]
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^2.1.2"
selenium = "^4.25.0"
bs4 = "^0.0.2"
pandas = "^2.2.3"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
