model:
  embedding_model: "all-MiniLM-L6-v2"
  cross_encoder_model: "cross-encoder/ms-marco-MiniLM-L-6-v2"
  llm_model: "Qwen/Qwen2.5-1.5B"

thresholds:
  reranking_threshold: 0.5
  quality_min_score: 0.5
  quality_min_docs: 1
  similarity_threshold: 0.7

vector_db:
  collection_name: "university_docs"
  top_k: 5

llm:
  max_length: 512
  temperature: 0.7
  top_p: 0.9
  repetition_penalty: 1.1